import numpy as np

SPEED_MULTIPLIER = 5

# Sphero Bolt Specs - MuJoCo
ENV_BOLT_MASS = 200
ENV_BOLT_MIN_ROTATION = -np.pi
ENV_BOLT_MAX_ROTATION = np.pi
ENV_BOLT_MIN_SPEED = 0 * SPEED_MULTIPLIER
ENV_BOLT_MAX_SPEED = 1 * SPEED_MULTIPLIER

# Soccer Ball Specs - MuJoCo
ENV_BALL_MASS = 2.77
ENV_BALL_MIN_SPEED = 0
ENV_BALL_MAX_SPEED = (ENV_BOLT_MASS * ENV_BOLT_MAX_SPEED * SPEED_MULTIPLIER) / (ENV_BALL_MASS) # assuming elastic collision 